In [1]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.


In [2]:
array1d= np.random.randint(10, 100, 50)
elementos_mult_5 = array1d[::5]
print(f"el array aleatorio de 1d es: \n {array1d}")
print("---------------------")
print(f"las posiciones con multiplos de 5 son: \n {elementos_mult_5}")

el array aleatorio de 1d es: 
 [92 63 87 72 39 48 54 35 33 44 71 63 37 21 40 41 52 18 88 55 25 35 42 57
 61 71 45 36 24 90 25 19 39 79 10 90 70 80 58 39 74 68 61 12 75 94 15 18
 11 54]
---------------------
las posiciones con multiplos de 5 son: 
 [92 48 71 41 25 71 25 90 74 94]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
array_1d= np.random.randint(1, 21, 30)
print(f"el array aleatorio de 1d es: \n {array_1d}")
print("---------------------")
print(f"Los elementos en posiciones impares del array son: \n {array_1d[1::2]}")

el array aleatorio de 1d es: 
 [15 16  9 11  3 10 13  1 18  1 13 12 17 12  6 14  9  2 19 20 13 12  8  3
 13  6 14 13 17 19]
---------------------
Los elementos en posiciones impares del array son: 
 [16 11 10  1  1 12 12 14  2 20 12  3  6 13 19]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [28]:
# con el uniform genera números decimales (float)
# en el uniform tenemos que especificarle el random: en este caso entre 0-90
#array_2d_float = np.random.uniform(0, 90, (4, 6))
#array_2d_float

# Crear un array 2D de forma (4, 6) con números decimales aleatorios, redondeados a 2 decimales
# con np.random.random también sale
array_2d_decimal = np.round(np.random.sample((4, 6)) * 100, 2)  # Multiplicamos por 100 para obtener decimales más variados

# Acceder a la última fila de la matriz
ultima_fila_decimal = array_2d_decimal[-1]

print("Array 2D completo:\n", array_2d_decimal)
print("------------------------")
print("Última fila de la matriz:", ultima_fila_decimal)

Array 2D completo:
 [[97.96 99.01 35.13  1.62 21.02 90.21]
 [10.51 62.28 26.1  62.76  3.77 16.74]
 [70.05 91.39 78.81 93.01 64.48 15.97]
 [82.89 83.85 58.46 94.9  17.49 82.96]]
------------------------
Última fila de la matriz: [82.89 83.85 58.46 94.9  17.49 82.96]


BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [33]:
array_3d= np.random.randint(0, 101, (2,3,5))
print(f" el array 3d es: \n {array_3d}")
array_3d_flat = array_3d.flatten()

# Reemplazar los elementos en posiciones múltiplos de 3 por 0 
array_3d_flat[::3] = 0 # Cada tercer elemento en el array plano se establece en 0
# Reconstruir el array 3D con los elementos modificados 
array_3d_modificado = array_3d_flat.reshape(2, 3, 5) 
print("\nArray 3D modificado:\n", array_3d_modificado)



 el array 3d es: 
 [[[ 75  31  94  61   6]
  [ 10 100  16 100  47]
  [ 19  33  53  99  11]]

 [[ 16  47  28  92  68]
  [ 44  74  70  85  46]
  [ 70  51  35  37   7]]]

Array 3D modificado:
 [[[  0  31  94   0   6]
  [ 10   0  16 100   0]
  [ 19  33   0  99  11]]

 [[  0  47  28   0  68]
  [ 44   0  70  85   0]
  [ 70  51   0  37   7]]]


In [35]:
#BONUS CON WHERE

array_3d= np.random.randint(0, 101, (2,3,5))
print(f" el array 3d es: \n {array_3d}")
array_3d_flat = array_3d.flatten()

# Reemplazar los elementos en las posiciones múltiplos de 3 
array_3d_flat = np.where(np.arange(array_3d_flat.size) % 3 == 0, 0, array_3d_flat)

np.arange(array_3d_flat.size)
# Volver a la forma 3D con el array modificado 
array_3d_modificado = array_3d_flat.reshape(2, 3, 5) 
print("\nArray 3D modificado:\n", array_3d_modificado)

 el array 3d es: 
 [[[ 56  65  64  33  65]
  [ 69  54  54  56  90]
  [ 44  67  82  99  24]]

 [[ 76 100  88  53  98]
  [ 29  73  61  17   0]
  [ 85  22  90  30  36]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Array 3D modificado:
 [[[  0  65  64   0  65]
  [ 69   0  54  56   0]
  [ 44  67   0  99  24]]

 [[  0 100  88   0  98]
  [ 29   0  61  17   0]
  [ 85  22   0  30  36]]]


# RESHAPE y TRANSPOSE


1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [37]:
array3d= np.random.randint(1, 101, (2,3,4))
array3d
# sabiendo que tenemos un total de 24 de elementos, necesitamos que se mantenga el número de elementos. 
array_2d = array3d.reshape(6,4)
array_2d

array([[77, 89, 45, 90],
       [42, 13, 70, 50],
       [26, 30, 94, 62],
       [90, 18, 67, 46],
       [95, 92, 37, 74],
       [24, 23, 20, 37]])